DROP TRIGGER "N_LU_CASE_STATUS_DTTM" ON "N_LU_CASE_STATUS";
DROP TRIGGER "N_NOTIFICATIONS_DTTM" ON "N_NOTIFICATIONS";
DROP TRIGGER "N_CASES_DTTM" ON "N_CASES";
DROP TRIGGER "N_LU_NOTIFICATION_STATUS_DTTM" ON "N_LU_NOTIFICATION_STATUS";

DROP FUNCTION SYNC_DB_CREATED_DTTM();

DROP TABLE "N_LU_CASE_STATUS" CASCADE;
DROP TABLE "N_CASES" CASCADE;
DROP TABLE "N_LU_NOTIFICATION_STATUS" CASCADE;
DROP TABLE "N_NOTIFICATIONS" CASCADE;

DROP SEQUENCE "N_CASES_ID_SEQ";
DROP SEQUENCE "N_NOTIFICATION_ID_SEQ";
