IF (EXISTS (SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE 
            WHERE TABLE_NAME = 'N_NOTIFICATIONS' AND CONSTRAINT_NAME = 'FK_CASE_ID__NOTIFICATIONS'))
BEGIN 
  ALTER TABLE [N_NOTIFICATIONS] DROP CONSTRAINT [FK_CASE_ID__NOTIFICATIONS]  ; 
END
  ELSE 
    BEGIN 
        PRINT 'CONSTRAINT ON N_NOTIFICATIONS NOT FOUND' 
    END;
GO


IF (EXISTS (SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE 
            WHERE TABLE_NAME = 'N_NOTIFICATIONS' AND CONSTRAINT_NAME = 'FK_STATUS_ID__NOTIFICATIONS'))
BEGIN  
  ALTER TABLE [N_NOTIFICATIONS] DROP CONSTRAINT [FK_STATUS_ID__NOTIFICATIONS]  ; 
END
  ELSE 
    BEGIN 
        PRINT 'CONSTRAINT ON N_NOTIFICATIONS NOT FOUND' 
    END;
GO


IF (EXISTS (SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE 
            WHERE TABLE_NAME = 'N_CASES' AND CONSTRAINT_NAME = 'FK_STATUS_ID__CASES'))
BEGIN 
  ALTER TABLE [N_CASES] DROP CONSTRAINT [FK_STATUS_ID__CASES]  ; 
END
  ELSE 
    BEGIN 
        PRINT 'CONSTRAINT ON N_CASES NOT FOUND' 
    END;
GO




IF (EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES
            WHERE TABLE_SCHEMA = 'DBO' AND  TABLE_NAME = 'N_NOTIFICATIONS'))
BEGIN 
    DROP TABLE [N_NOTIFICATIONS] ;
END
  ELSE 
    BEGIN 
        PRINT 'TABLE N_NOTIFICATIONS NOT FOUND' 
    END;
GO

IF (EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES
            WHERE TABLE_SCHEMA = 'DBO' AND  TABLE_NAME = 'N_LU_NOTIFICATION_STATUS'))
BEGIN 
    DROP TABLE [N_LU_NOTIFICATION_STATUS] ;
END
  ELSE 
    BEGIN 
        PRINT 'TABLE N_LU_NOTIFICATION_STATUS NOT FOUND' 
    END;
GO

IF (EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES
            WHERE TABLE_SCHEMA = 'DBO' AND  TABLE_NAME = 'N_CASES'))
BEGIN 
    DROP TABLE [N_CASES] ;
END
  ELSE 
    BEGIN 
        PRINT 'TABLE N_CASES NOT FOUND' 
    END;
GO


IF (EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES
            WHERE TABLE_SCHEMA = 'DBO' AND  TABLE_NAME = 'N_LU_CASE_STATUS'))
BEGIN 
    DROP TABLE [N_LU_CASE_STATUS] ;
END
  ELSE 
    BEGIN 
        PRINT 'TABLE N_LU_CASE_STATUS NOT FOUND' 
    END;
GO




IF (EXISTS (SELECT SEQUENCE_NAME FROM INFORMATION_SCHEMA.SEQUENCES
            WHERE SEQUENCE_NAME = 'N_SEQ_CASES_PK'))
BEGIN 
    DROP SEQUENCE N_SEQ_CASES_PK;
END
  ELSE 
    BEGIN 
        PRINT 'SEQUENCE N_SEQ_CASES_PK NOT FOUND' 
    END;
GO


IF (EXISTS (SELECT SEQUENCE_NAME FROM INFORMATION_SCHEMA.SEQUENCES
            WHERE SEQUENCE_NAME = 'N_SEQ_NOTIFICATIONS_PK'))
BEGIN 
    DROP SEQUENCE N_SEQ_NOTIFICATIONS_PK;
END
  ELSE 
    BEGIN 
        PRINT 'SEQUENCE N_SEQ_NOTIFICATIONS_PK NOT FOUND' 
    END;
GO