
DROP PUBLIC SYNONYM N_NOTIFICATIONS FORCE;
/

DROP PUBLIC SYNONYM N_LU_CASE_STATUS FORCE;
/

DROP PUBLIC SYNONYM N_CASES FORCE;
/

DROP PUBLIC SYNONYM N_LU_NOTIFICATION_STATUS FORCE;
/

DROP SEQUENCE N_SEQ_CASES_PK;

DROP SEQUENCE N_SEQ_NOTIFICATIONS_PK;
/

ALTER TABLE N_NOTIFICATIONS
DROP PRIMARY KEY CASCADE  DROP INDEX;
/

ALTER TABLE N_LU_NOTIFICATION_STATUS
DROP CONSTRAINT N_XAK_LU_NOTIFICATION_STATUS CASCADE  DROP INDEX;
/

ALTER TABLE N_LU_NOTIFICATION_STATUS
DROP PRIMARY KEY CASCADE  DROP INDEX;
/

ALTER TABLE N_CASES
DROP PRIMARY KEY CASCADE  DROP INDEX;
/

ALTER TABLE N_LU_CASE_STATUS
DROP PRIMARY KEY CASCADE  DROP INDEX;
/

ALTER TABLE N_LU_CASE_STATUS
DROP CONSTRAINT N_XAK_LU_CASE_STATE CASCADE  DROP INDEX;
/

DROP TRIGGER N_TRG_NOTIFICATIONS_UPDATE
;
/

DROP TRIGGER N_TRG_NOTIFICATIONS_INSERT
;
/

DROP TRIGGER N_TRG_CASES_UPDATE
;
/

DROP TRIGGER N_TRG_CASES_INSERT
;
/

DROP TRIGGER N_TRG_NOTIFICATIONS_SEQ
;
/

DROP TRIGGER N_TRG_CASES_SEQ
;
/

DROP INDEX N_XPK_NOTIFICATIONS;
/

DROP INDEX N_XIF_NOTIFICATIONS_CASES;
/

DROP INDEX N_XIF_NOTIFICATIONS_STATUS;
/

DROP TABLE N_NOTIFICATIONS CASCADE CONSTRAINTS PURGE;
/

DROP INDEX N_XAK_LU_NOTIFICATION_STATUS;
/

DROP INDEX N_XPK_LU_NOTIFICATION_STATUS;
/

DROP TABLE N_LU_NOTIFICATION_STATUS CASCADE CONSTRAINTS PURGE;
/

DROP INDEX N_XPK_CASES;
/

DROP INDEX N_XAK_CASES_GUID;
/

DROP INDEX N_XIF_CASES;
/

DROP TABLE N_CASES CASCADE CONSTRAINTS PURGE;
/

DROP INDEX N_XPK_LU_CASE_STATUS;
/

DROP INDEX N_XAK_LU_CASE_STATE;
/

DROP TABLE N_LU_CASE_STATUS CASCADE CONSTRAINTS PURGE;
/

exit
